### PR TITLE
Remove build chain

### PR DESCRIPTION
**Pull request by Taylor123**

### CODE REVIEW

**Comment by tomjohn1028** [comment]
Screen Shot 2021-11-16 at 11 00 10 PM


@Taylor123 the strikes are all off. looks like it's just a toFixed issue or something with the decimals

**Comment by tomjohn1028** [comment]
Screen Shot 2021-11-16 at 11 08 27 PM

BTC Contract sizes that don't exist are showing up

**Comment by tomjohn1028** [comment]
Screen Shot 2021-11-17 at 9 13 59 AM

Loading markets page results in errors

**Comment by Taylor123** [comment]
Haven't been able to reproduce the last issue. It would be a type error, but i'm not seeing one related to the function returned from that hook. Would need to see a full stack trace

**Pull request merged**
